// Stickman Kino - export standalone text-to-video prompts (Gemini Omni Flash / Veo / Sora / Kling …)
// from film.json, so the same storyboard can also be generated as AI footage.
// Prompt structure follows the open "Stickman Video Director" method by kaomei (MIT) - see THIRD_PARTY_NOTICES.md.
import fs from "node:fs";
import path from "node:path";
import { loadFilm, readManifest, timings } from "./film.mjs";

const STYLE = {
  light: { env: "Environment: a flat, uniform, digitally pure-white canvas with no textures, no gradients, no shading, no 3D depth.", char: "a minimalist 2D stick figure with a hollow circular head, no facial features, no hair, no clothing, no filled body, uniform medium black line weight" },
  dark: { env: "Environment: a flat, uniform, pitch-black canvas with pure white line art.", char: "a minimalist 2D stick figure drawn in pure white lines with a hollow circular head, no facial features, no clothing, uniform medium line weight" },
  studio: { env: "Environment: a modern bright white studio space with subtle light-gray perspective grid lines on the floor plane, high-key studio lighting, clean white negative space, sleek glowing cyan and electric blue glass holographic UI elements. Strictly minimalist: no circuit-board textures, no sci-fi wall panels, no cracked concrete.", char: "a minimalist 2D animated stick figure wearing a bright red beanie (smooth knit, no pom-pom) and a yellow t-shirt, with simple black stick limbs and shorts; simple black lines, vibrant colors, smooth 2D animation style" },
  paper: { env: "Environment: a warm off-white paper canvas with faint paper grain, hand-drawn ink line art, no 3D depth.", char: "a hand-drawn ink stick figure with a hollow circular head, no facial features, uniform marker line weight" },
  chalkboard: { env: "Environment: a dark green school chalkboard filling the frame, white chalk line art with soft chalk texture.", char: "a chalk-drawn stick figure with a hollow circular head, no facial features, uniform chalk line weight" },
  blueprint: { env: "Environment: a deep blue engineering blueprint with a faint white grid, crisp white technical line art.", char: "a white technical-line stick figure with a hollow circular head, no facial features, uniform line weight" },
  neon: { env: "Environment: a pitch-black canvas with glowing neon line art (pink, cyan, yellow glow).", char: "a glowing white neon-line stick figure with a hollow circular head, no facial features" },
  sunset: { env: "Environment: a warm peach-to-cream gradient sky with a soft low sun, flat 2D illustration.", char: "a minimalist dark-plum line stick figure with a hollow circular head, no facial features" }
};
const COLORNAMES = ["vivid red", "electric blue", "warm gold"];

export function exportPrompts(dir, o) {
  o = o || {}; const film = loadFilm(dir), { clips } = timings(film, readManifest(dir));
  const themeName = typeof film.theme === "string" ? film.theme : (film.theme && film.theme.extends) || "light";
  const st = STYLE[themeName] || STYLE.light, ratio = film.format || "16:9";
  const voice = (film.promptVoice || "confident, articulate, warm young adult American male voice, natural conversational storytelling tone, voice-first mix");
  const MUSIC = { "calm-piano": "quiet, thoughtful piano and subtle soft ambient synth, building gentle optimistic momentum", uplifting: "bright plucked synths over a steady soft kick and claps, optimistic and energetic", corporate: "a driving pulse synth with light piano chords and a soft four-on-the-floor beat", lofi: "warm lo-fi Rhodes chords with lazy swung drums and soft vinyl crackle", playful: "a bouncy ukulele with glockenspiel accents, pizzicato bass and finger snaps", suspense: "a low sustained drone with soft ticking and a minor-key pulse", epic: "big cinematic strings with deep taiko drums, building to a climax", ambient: "airy ambient pads with sparse soft bells" };
  const music = (film.music && film.music.promptDesc) || MUSIC[(film.music && film.music.style) || "calm-piano"] || MUSIC["calm-piano"];
  const neg = "Negative constraints: no photorealism, no 3D humanoid rendering, no facial features unless specified, no extra limbs, no malformed anatomy, no changing line weight or proportions, no extra characters, no abstract liquid or shape morphing, no visible words, letters, numbers, captions, subtitles, logos or watermarks, no speech bubbles, no dialogue text boxes.";
  const out = [`# ${film.title || "Film"} - text-to-video prompt package`, "", `Generated by \`stickman prompts\` from film.json · ${ratio} · ${clips.length} clips · theme ${themeName}.`, "", "Paste each prompt into Google Flow (Gemini Omni Flash / Veo), Sora, Kling or Runway. Clips are ~" + Math.round(clips[0].duration) + " s each. For the most consistent voice and music, keep only the clip SFX and lay the film's own VO + music bed (assets/) over the stitched result.", ""];
  clips.forEach((cl, i) => {
    const beats = (cl.beats || []).map(b => `- [${b.t}] ${b.do}`).join("\n") || `- [0-3s] ${cl.visual ? "establish the scene above with a clear entrance and the main object visible" : "the stick figure establishes the idea of this beat with a concrete physical action"}\n- [3-7s] the figure interacts with an oversized, relevant object that makes the idea visible\n- [7-${Math.round(cl.duration)}s] a clear payoff action, then motion that carries into the next clip`;
    out.push(`## Clip ${i + 1} · ${cl.label || cl.id} (${cl.start.toFixed(1)}-${(cl.start + cl.duration).toFixed(1)} s)`, "", "```text",
      `Output: approximately ${Math.round(cl.duration)} seconds, ${ratio}, 720p target, 24 FPS, synchronized audio.`,
      st.env,
      `Character lock: ${i === 0 ? "" : "the same "}${st.char}. Stable proportions; the same single character throughout.`,
      `Palette: line art plus at most three saturated accents used by meaning - ${COLORNAMES.join(", ")}.`,
      ratio === "9:16" ? "Composition (9:16): vertical depth, stacked motion, bold central silhouette, keep the top and bottom fifths clear." : "Composition (16:9): stage action across left, centre and right thirds; lateral tracking; generous negative space.",
      "Style language: rapid scene changes, kinetic motion-graphic transformations and frequent visual events, while preserving an identical stick-figure design, constant line weight and strict temporal consistency.",
      cl.visual ? `Scene: ${cl.visual}` : "",
      "Timed visual beats:", beats,
      cl.vo ? `Dialogue (audio voiceover only, spoken exactly once, no captions): "${cl.vo}"` : "No dialogue.",
      `Identical narrator: ${voice}. Audio voiceover only, strictly no speech bubbles or dialogue boxes.`,
      i === 0 ? `Audio: voiceover clearly audible over ${music}.` : `Audio: voiceover seamlessly continues the identical ${music} from clip 1, same tempo and instrumentation. Synchronized crisp SFX on physical actions.`,
      i < clips.length - 1 ? `Final frame: hold a pose or motion that the next clip (${clips[i + 1].label || clips[i + 1].id}) can open on.` : "Final frame: a settled, fully composed hold.",
      neg, "```", "");
  });
  const file = path.join(dir, o.out || "prompts.md"); fs.writeFileSync(file, out.filter(l => l !== null).join("\n")); return file;
}
